local tex = require('compilers.tex')
vim.keymap.set('n', '<leader>ll', function()
        local buf = vim.api.nvim_get_current_buf()
        tex.toggle_compilation(buf)
end, { buf = 0 })
vim.keymap.set('n', '<leader>lk', function()
        local buf = vim.api.nvim_get_current_buf()
        tex.view_one(vim.fs.normalize(vim.api.nvim_buf_get_name(buf)))
end)
vim.keymap.set('n', '<leader>la', function()
        local buf = vim.api.nvim_get_current_buf()
        tex.view_all(vim.fs.normalize(vim.api.nvim_buf_get_name(buf)))
end)
